name: cd-samples

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Login to ACR
        uses: docker/login-action@v3
        if: github.event_name == 'workflow_dispatch'
        with:
          registry: sdkagents.azurecr.io
          username: pusher
          password: ${{ secrets.ACR_PUSHER_TOKEN }}

      - name: Install Node dependencies
        run: npm install
        working-directory: ./samples

      - name: Run lint
        run: npm run lint
        working-directory: ./samples

      - name: Build Node Copilot Studio client sample
        working-directory: ./samples/basic/copilotstudio-client/nodejs/
        run: |
          npm install
          npm run build
      
      - name: Build docker image dotnet Echo bot
        working-directory: ./samples/basic/empty-agent/dotnet/
        run: |
          dotnet publish /t:PublishContainer /p:ContainerRepository=dotnet-echo-bot --os linux --arch x64

      - name: Push image dotnet Echo bot
        if: github.event_name == 'workflow_dispatch'
        working-directory: ./samples/basic/empty-agent/dotnet/
        run: |
          docker tag dotnet-echo-bot:latest sdkagents.azurecr.io/dotnet-echo-bot:latest
          docker push sdkagents.azurecr.io/dotnet-echo-bot:latest

      - name: Build docker image Node Empty Agent
        working-directory: ./samples/basic/empty-agent/nodejs/
        run: |
          npm install
          npm run docker

      - name: Push image Node Empty Agent
        if: github.event_name == 'workflow_dispatch'
        working-directory: ./samples/basic/empty-agent/nodejs/
        run: |
          docker tag node-empty-agent:1.0.0 sdkagents.azurecr.io/node-empty-agent:latest
          docker push sdkagents.azurecr.io/node-empty-agent:latest

      - name: Build docker image Node Cards bot
        working-directory: ./samples/basic/cards/nodejs/
        run: |
          npm install
          npm run docker

      - name: Push image Node Cards Agent
        if: github.event_name == 'workflow_dispatch'
        working-directory: ./samples/basic/cards/nodejs/
        run: |
          docker tag node-cards-agent:1.0.0 sdkagents.azurecr.io/node-cards-agent:latest
          docker push sdkagents.azurecr.io/node-cards-agent:latest

      - name: Build docker iamge Node Skill bot
        working-directory: ./samples/complex/copilotstudio-skill/nodejs/
        run: |
          npm install
          npm run docker

      - name: Push image Node Skill
        if: github.event_name == 'workflow_dispatch'
        working-directory: ./samples/complex/copilotstudio-skill/nodejs/
        run: |
          docker tag node-echo-skill:1.0.0 sdkagents.azurecr.io/node-echo-skill:latest
          docker push sdkagents.azurecr.io/node-echo-skill:latest
      
      - name: Build docker iamge Node Weather Agent
        working-directory: ./samples/basic/weather-agent/nodejs/
        run: |
          npm install
          npm run docker

      - name: Push image Node Weather Agent
        if: github.event_name == 'workflow_dispatch'
        working-directory: ./samples/basic/weather-agent/nodejs/
        run: |
          docker tag node-weather-agent:1.0.0 sdkagents.azurecr.io/node-weather-agent:latest
          docker push sdkagents.azurecr.io/node-weather-agent:latest
