name: ci-node

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: Install dependencies
        run: npm install
        working-directory: ./samples

      - name: Run lint
        run: npm run lint
        working-directory: ./samples

      - name: Build Echo bot
        working-directory: ./samples/basic/echo-bot/nodejs/
        run: |
          npm install
          npm run build

      - name: Build Cards bot
        working-directory: ./samples/basic/cards/nodejs/
        run: |
          npm install
          npm run build

      - name: Build Copilot Studio client sample
        working-directory: ./samples/basic/copilotstudio-client/nodejs/
        run: |
          npm install
          npm run build

      - name: Build Skill bot
        working-directory: ./samples/complex/copilotstudio-skill/nodejs/
        run: |
          npm install
          npm run build